### ISSUE TITLE
Ocne handler called more then once

### ISSUE THREAD

**Issue by knobo** [fukamachi/event-emitter#6]
How to reproduce
``` cl
(defpackage :bug
  (:use :cl :event-emitter))

(in-package :bug)

(defclass bug (event-emitter)
  ())

(defparameter *beatle*
  (make-instance 'bug))

(on   :creep *beatle* (lambda () (format t "tik, ")))
(once :creep *beatle* (lambda () (format t "squeak, ")))
(once :creep *beatle* (lambda () (format t "peep, ")))
(once :creep *beatle* (lambda () (format t "cheep, ")))
(on   :turn  *beatle* (lambda () (format t "~%")))

(emit :creep *beatle* )
(emit :turn *beatle*)
(emit :creep *beatle* )

;; output:

tik, squeak, cheep, cheep, 
tik, peep, 

;; But what I expected: 

tik, squeak, peep, cheep, 
tik,

```

Fixed in: #5

**Comment by anranyicheng** [comment]
Hi, after this fixes https://github.com/fukamachi/event-emitter/commit/fea2603f009378678312e4c7fb3c247b76b72f3d, the result is also not correct. I fix code there:
(defun remove-listener (object event listener &key(start 0))
(let* ((silo (silo object))
(listeners (gethash event silo)))
(unless listeners
(return-from remove-listener))
(setf (gethash event silo)
(delete listener listeners
:test #'eq
:count 1
:start start
:key #'listener-function)))
(values))

(defun emit (event object &rest args)
(let* ((listeners (listeners object event))
(max-size (length listeners)))
(when (zerop max-size)
(return-from emit nil))
(dotimes (indx (length listeners))
(apply (listener-function (elt listeners indx)) args))
(do ((indx 0 (1+ indx)))
((>= indx max-size))
(when (listener-once (elt listeners indx))
(remove-listener object event (listener-function(elt listeners indx))
:start indx)
(decf max-size)
(decf indx)))
t))
then ,the result is right.
